agent_name: lst_agent_prod
author: lstolas
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.55.0, <2.0.0'
fingerprint:
  logger_setup.py: bafybeicboqnvizlhdsnmlncvayrswskbyw6vshi34bnrs75qshbz3wdlqu
  no-queue-logging.yaml: bafybeib6k2usocdkxtz6nqa2igxbwkp7f72inrsxtufyy3pttpbojxysay
  tests/__init__.py: bafybeibk76alseqt3ufreyev7rnz5zuk6dcftt7c2ob54gmhpt6xrhkg2y
  tests/test_agent.py: bafybeicyppqui4vd7vo2s4kbgaposbtckwp76t3bjeoztjhcwlxqe7woxm
fingerprint_ignore_patterns: []
connections:
- eightballer/http_client:0.1.0:bafybeiaz5auftwxpt4czrmeeesggqlkc2kosmetq6adrebeu6g7bkhqc2u
- eightballer/http_server:0.1.0:bafybeidrvllrr23mc6bvjxn6v3hny6oiwhfgi72n2b7w6ck5luousjfbbq
- eightballer/prometheus:0.1.1:bafybeicy4ck2wvauo2vh6ji64xrzlgezh27powi6ztokr4yujtf3cft6wi
- eightballer/apprise_wrapper:0.1.0:bafybeibekoqsadyztskr353x3usoxe4bmjlr45ecafmyfbxay6dc4jxcci
contracts: []
protocols:
- eightballer/default:0.1.0:bafybeicsdb3bue2xoopc6lue7njtyt22nehrnkevmkuk2i6ac65w722vwy
- eightballer/http:0.1.0:bafybeid75xhq7hfdt7sgj7yrn44yj57xrgxscaw34ir46tndfzvodioxme
- eightballer/prometheus:1.0.0:bafybeidxo32tu43ru3xlk3kd5b6xlwf6vaytxvvhtjbh7ag52kexos4ke4
- eightballer/user_interaction:0.1.0:bafybeidmfy3vdnlbz6wexi4gwhofown4a7l6jt7nzh2x7lvghumxlgh4vi
- open_aea/signing:1.0.0:bafybeig2d36zxy65vd7fwhs7scotuktydcarm74aprmrb5nioiymr3yixm
skills:
- eightballer/prometheus:0.1.0:bafybeicl5i7e467aowfarke4bbyixo2dggar276njmvyuwbsby5pxshhtu
- lstolas/lst_skill:0.1.0:bafybeib7w5i5unvxx7fvrb5ypao62kb2rhxvjeaqowx3b34udbwzuo453y
customs: []
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  handlers:
    queue:
      class: logger_setup.QueuedHandler
      queue_size: 10000
      handler_names:
      - console
      - logfile
      handler_configs:
        console:
          class: logger_setup.BufferedHandler
          formatter: standard
          level: INFO
        logfile:
          class: logging.handlers.TimedRotatingFileHandler
          filename: log.jsonl
          formatter: json
          level: INFO
          when: D
          interval: 1
          backupCount: 7
      formatter_configs:
        standard:
          class: logger_setup.ShortNameFormatter
          format: '[%(levelname)s] %(asctime)s: %(message)s'
          datefmt: '%Y-%m-%dT%H:%M:%S'
        detailed:
          format: '[%(levelname)s|%(pathname)s|L%(lineno)d] %(asctime)s: %(message)s'
          datefmt: '%Y-%m-%dT%H:%M:%S%z'
        json:
          class: logger_setup.JSONFormatter
          datefmt: '%Y-%m-%dT%H:%M:%S%z'
  loggers:
    aea:
      handlers:
      - queue
      level: INFO
      propagate: false
  version: 1
dependencies:
  open-aea-ledger-cosmos: {}
  open-aea-ledger-ethereum: {}
  rich: {}
default_connection: null
period: 1.0
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: lstolas/lst_abci_app:0.1.0
---
public_id: eightballer/apprise_wrapper:0.1.0
type: connection
config:
  endpoints:
  - ${APPRISE_ENDPOINT:str:null}
---
public_id: lstolas/lst_skill:0.1.0:bafybeib7w5i5unvxx7fvrb5ypao62kb2rhxvjeaqowx3b34udbwzuo453y
type: skill
models:
  lst_strategy:
    args:
      layer_1_rpc_endpoint: https://eth.drpc.org
      layer_1_amb_home: '0x4C36d2919e407f0Cc2Ee3c993ccF8ac26d9CE64e'
      layer_1_olas_address: '0x0001A500A6B18995B03f44bb040A5fFc28E45CB0'
      layer_2_rpc_endpoint: https://gnosis.drpc.org
      layer_2_amb_home: '0x75Df5AF045d91108662D8080fD1FEFAd6aA0bb59'
      layer_2_amb_helper: '0x7d94ece17e81355326e3359115D4B02411825EdD'
      lst_collector_address: '0x64003846B67D66AfdFb03325fa4292b76FCF182F'
      lst_unstake_relayer_address: '0xaC7eA9478E0e1186E7D1c82b8d8dc80AEe0F79F6'
      lst_distributor_address: '0x64003846B67D66AfdFb03325fa4292b76FCF182F'
      lst_staking_manager_address: '0xEfF4A1D9faF5c750d5E32754c40Cf163767C63A4'
      lst_staking_processor_l2_address: '0x4A26F79b9dd73a48d57ce4DF70295A875afa006c'
